name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install packages ğŸ“¦
        run: |
          yarn --pure-lockfile
      - name: Build site ğŸ”§
        run: |
          yarn run build
      - name: Deploy to Github Pages ğŸš€
        run: |
          yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}